onvif:
  # Replace with actual MAC address of the Pi network interface
  - mac: 00:22:b0:6c:a8:ef
    ports:
      server: 8081
      rtsp: 8555
      # snapshot: 8580
    name: PiCamera
    uuid: c2647db1-e326-11f0-b97a-b827ebb9e46d
    # The 'target' is the actual source of the video
    target:
      hostname: 127.0.0.1
      ports:
        rtsp: 8554
        snapshot: 80
    highQuality:
      rtsp: /cam
      # snapshot: /onvif/snapshot?channel=1&subtype=0
      width: 800
      height: 600
      framerate: 5
      bitrate: 1000
      quality: 4
    lowQuality:
      rtsp: /cam
      # snapshot: /onvif/snapshot?channel=1&subtype=1
      width: 800
      height: 600
      framerate: 5
      bitrate: 1000
      quality: 1